### PR TITLE
P4U2.ron Updated

### PR DESCRIPTION
**Pull request by jeffdiom**
I got most of the unknowns labeled. For now, this should be good enough.

### CODE REVIEW

**Comment by jeffdiom** [comment]
I'm still going to work on it in the future.

**Comment by super-continent** [comment]
try changing the line endings in the file so it doesnt render the whole file being modified

**Comment by jeffdiom** [comment]
I'm getting the unknown30000s because without it rise can't be parse. It is for her rhythm game super.

**Comment by jeffdiom** [comment]
Rise can't be parse at all because the .ron is missing the unknowns 30000 -> 30019

**Comment by jeffdiom** [comment]
It is for her rhythm game super

**Comment by super-continent** [comment]
Merged, thanks for all the labels! It's really helpful

**Pull request merged**
